version: "3.7"
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql-container
    environment: 
      MYSQL_ROOT_PASSWORD: laravelpass    
    restart: always
  laravel: 
    image: laravel:1.0
    container_name: laravel
    restart: unless-stopped
    tty: true
    volumes:
      - //D//Diego/Documents/GIT/curso_laravel:/home/diego
    ports:
      - "8000:8000"
      - "4200:4200"