version: "3.7"
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql-container
    environment: 
      MYSQL_ROOT_PASSWORD: laravelpass
    volumes:
      - /home/diego/Projetos/banco_de_dados
    restart: always
  laravel: 
    image: laravel:1.0
    container_name: laravel
    restart: unless-stopped
    tty: true
    volumes:
      - /home/diego/Projetos/PHP/Estudos_Laravel/cadastroAjax:/home/cadastroAjax
    ports:
      - "8000:8000"
